spring:
  cloud:
    stream:
      bindings:
        # <name>-in-0 must match the name in function.definition
        consumer-in-0:
          destination: ${EVENTHUB_NAME}
          group: ${EVENTHUB_CONSUMER_GROUP_NAME:$Default}
      eventhubs:
        bindings:
          # <name>-in-0 must match the name in function.definition
          consumer-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      function:
        definition: consumer;
